Don't fix rake to any version in gemspec
To avoid error:
```
  bundle exec rake test
  shell: /usr/bin/bash -e {0}
rake aborted!
NoMethodError: undefined method `=~' for an instance of Proc
/home/runner/work/jemquarie/jemquarie/vendor/bundle/ruby/3.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```

https://app.asana.com/0/1205428368058391/1206747143442454/f