Bump to rubocop 1.59.0 to follow investapp
And resolve error:
```
Error: RuboCop found unknown Ruby version 3.3 in `TargetRubyVersion` parameter (in .rubocop.yml).
Supported versions: 2.5, 2.6, 2.7, 3.0, 3.1
```

https://app.asana.com/0/1205428368058391/1206747143442454/f